[project]
name = "uc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "forex-python>=1.8",
    "pint>=0.24.4",
    "streamlit>=1.44.1",
]
